MONGODB_HOST: mongodb.devopswithdinesh.shop
REDIS_HOST: redis.devopswithdinesh.shop
CATALOGUE_HOST: catalogue.devopswithdinesh.shop
CART_HOST: cart.devopswithdinesh.shop
USER_HOST: user.devopswithdinesh.shop
RABBITMQ_HOST: rabbitmq.devopswithdinesh.shop
MYSQL_HOST: mysql.devopswithdinesh.shop
SHIPPING_HOST: shipping.devopswithdinesh.shop
PAYMENT_HOST: payment.devopswithdinesh.shop